import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ProgressProvider } from "@/contexts/ProgressContext";
import { mockLessons } from "@/features/Workspace/mock-lessons";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// Extract only the metadata we need (id and skillNodeId) from lessons
const lessonMetadata = mockLessons.map((lesson) => ({
	id: lesson.id,
	skillNodeId: lesson.skillNodeId,
}));

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} antialiased`}>
				<ProgressProvider lessonMetadata={lessonMetadata}>
					{children}
				</ProgressProvider>
			</body>
		</html>
	);
}
